#Configuración para base de datos
database:
  user: userdb
  pass: passdb
  host: mongo_host
  port: 27017
  name: namedb

#Configuración servidor
server:
  port: 2000
  host: backend_host
  logfile: logfile.log
  logpath: /opt/visor/logs/

#Parámetros autentificación
auth:
  session:
    path: /api #Primera ruta despues del dominio
    maxage: 300000 #Segundos. Este tiempo debería ser el mismo que para la expiración del JWT
    httponly: true
    secretkey: asadasd
  jwt:
    exp: 5000 #Minutos. Este tiempo debería ser el mismo que para la expiración de la cookie
    secretkey: asadasd

#Parámetros API Rest
apirest:
  page: 0
  size: 15

#Parámetros para el envío de correos
mail:
  smtp: smtp.gmail.com
  port: 465
  sender: mail@gmail.com
  password: passwordmail

#Configuración GeoServer
geoserver:
  host: http://geoserver_host:8600/geoserver
  layerspath: /
  postpath: /rest/workspaces/visor_upload/datastores/tmp/file.shp
  user: admin
  password: geoserver

#Configuración CORS
cors:
  origin: http://localhost:8084
#Como se usa en producción, no se puede limitar 